[package]
name = "rec-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "rec"
path = "src/main.rs"

[dependencies]
rec = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
clap = { version = "4.5.41", features = ["derive"] }